name: proviso
description: Complete set of tools for widgets conditional rendering and wrapping.
version: 1.0.2
homepage: https://github.com/AlexeyPerov/proviso

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

